spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email
  jwt:
    secret: fjdsioafjdsaiofjoiwjhqowijdsoidsdjfd

  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true